### ISSUE TITLE
PiGlow software installation instructions need updating for DT/raspi-config

### ISSUE THREAD

**Issue by DeeJay** [raspberrypilearning/piglow#9]
http://www.raspberrypi.org/learning/piglow/software.md needs updating to take account of control of i2c by Device Tree: need to use option in raspi-config to enable before first use.

[This may be one of several similar issues arising from the implementation of DT: perhaps this issue could be converted into a 'placeholder' to accumulate such comments?]

**Comment by MissPhilbin** [comment]
@bennuttall has this issue been resolved?

**Comment by bennuttall** [comment]
I know nothing about the new Device Tree stuff. I'll have to ask @pelwell what we need to do.

**Comment by pelwell** [comment]
Run raspi-config, go to Advanced Options, select I2C, say Yes to enabling the interface, say Yes to loading the module automatically.

I suggest you try it, to be sure the steps are correct.

**Comment by darrell24015** [comment]
There is a work-around mentioned at the end of this thread where you can manually edit the /boot/config.txt file (probably what gets done with the raspi-config procedure?):
http://www.raspberrypi.org/forums/viewtopic.php?f=45&t=89936

**Comment by pelwell** [comment]
Yes, it's not a workaround, it's just typing instead of using a menu. Plus raspi-config uses the recommended name - i2c_arm.

**Comment by darrell24015** [comment]
Indeed, I just tried the steps you mentioned above and worked exactly as described. Also found the documentation on Device Tree. Thanks!

**Comment by bennuttall** [comment]
I've just added the raspi-config instruction to the setup. See [software.md](https://github.com/raspberrypilearning/piglow/blob/master/software.md) - does that look right to everyone? @DeeJay @pelwell @gadgetoid

**Comment by pelwell** [comment]
The new raspi-config options replace the need to manually edit the blacklist file, so you can remove that section.

Others:
"Then either add the following line is at the end of the file, if it's not already there:"
"when propted"

**Comment by bennuttall** [comment]
Thanks, fixed.

**Comment by Gadgetoid** [comment]
This is related to a rather wider issue that we've got with PiGlow- the presence of about 4 different Python libraries for the same device. PiGlow is one of our most popular boards, and we're getting a lot of feedback/confusion with the install process.

I'd like our installer, plus the repository I am currently working on, to be the canonical solution, but it's not yet ready for prime time.

The current state of affairs is: https://github.com/Gadgetoid/python-piglow

It's compatible with Boeeerb's examples since his library is currently in pip, but I haven't tested it against PyGlow.

The installer script, found here https://github.com/pimoroni/get/blob/master/piglow, does everything from enabling i2c, to checking and installing pre-requisites and then downloading examples into ~/Pimoroni/piglow.

**Comment by bennuttall** [comment]
Excellent - I'm in favour. Will be happy to adapt this to the official one when it's ready.
